project:
  type: website
  output-dir: docs  
  resources:
    - resources/
    - career_talk/

website:
  title: "Terry O'Malley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: talks.qmd 
        text: Talks